### ISSUE TITLE
Controller assets from kenney.nl

### ISSUE THREAD

**Issue by ShadowMitia** [icculus/ControllerImage#22]
Relating to controller art, [Kenney](https://kenney.nl/) is currently working on [controller assets](https://mastodon.gamedev.place/@kenney/111523255360220217)  which will be published under CC0 (public domain).
As far as I understand these will only be input prompts, but it covers "all common controllers, plus keyboard and mouse".

No publication date scheduled yet, but I expect it'll be a couple of months before they are ready.

**Comment by icculus** [comment]
I've been watching Kenney's work on Twitter!

When he's done, we'll likely pull it into this project as its own theme, so developers can choose it as their primary art set if they want.

**Comment by ShadowMitia** [comment]
The assets have been published here: https://kenney.nl/assets/input-prompts !

**Comment by icculus** [comment]
These are in now!
